name: Clangd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
    - name: Install essential packages
      run: sudo apt-get install -y ninja-build cmake

    - name: Show current directory
      run: |
        pwd
        ls

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../llvm/ -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
        cmake --build ./ --target clangd
