name: Clangd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
    - name: Install essential packages
      run: sudo apt-get install -y ninja-build cmake

    - name: Show current directory
      run: |
        pwd
        ls
